export default {
  // user
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  // channel
  SET_CHANNEL_COLLECTION: 'SET_CHANNEL_COLLECTION',
  SET_CURRENT_CHANNEL: 'SET_CURRENT_CHANNEL',
  SET_PRIVATE_CHANNEL: 'SET_PRIVATE_CHANNEL'
};
